### ISSUE TITLE
Acknowledging contributors and editors

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-data#1]
Hi, @wsalesky! I've been regularizing our contribution indicators, so we can display all the contributors and editors in a page, as well as search for/browse contributor and editor additions--see /haywood/haywood-fantomina.xml and finch/finch-nightingale.xml for models. The information is included in the teiHeader under titleStmt/editor and /titleStmt/respStmt, and then in the //note elements, as indicated: 

- `            <editor>
               <persName type="orcid" key="0000-0002-7400-4093"><name ref="editors.xml#TH"><forename>Tonya</forename> <surname>Howe</surname></name></persName>
            </editor>
            <respStmt>
               <resp>Transcription, correction, editorial commentary, and markup</resp>
               <name ref="editors.xml#MUstudstaff">Students of Marymount University</name>
               <name ref="editors.xml#JW"><forename>James</forename> <surname>West</surname></name>
               <name ref="editors.xml#AR"><forename>Amy</forename> <surname>Ridderhof</surname></name>
            </respStmt>`

- `@who="editors.xml#JW"`
- `@ref="editors.xml#MUstudstaff"`
- `<note xml:id="n005" target="a005" type="editorial" resp="editors.xml#JW">`

Does this look like a logical approach?

We also now have an editors.xml page!

**Comment by wsalesky** [comment]
@tonyahowe Yes that looks good to me.
