### ISSUE TITLE
Equiano

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-data#14]
@jobrien62 @sb8wb Hi, John and Sara! I have been playing around with the display issues in Equiano, and I think I have a solution. Check out [https://anthologydev.lib.virginia.edu/work/Equiano/equiano-interesting-narrative-test](https://anthologydev.lib.virginia.edu/work/Equiano/equiano-interesting-narrative-test). Since this has the two volumes in one text, it makes sense to use parent `<div>`s to house each volume. If you do an outline search in Oxygen for `<div>`, you'll see the structure. I also regularized the `<floatingText>`s, eliminated the hyphenation not necessary for sense, and the extra line breaks throughout. See the github commit history for all details! There is one page image that's not quite right - volume 1 page xxii is not there; instead, the page that is is xii.

**Comment by jobrien62** [comment]
Tonya:

Thanks for coming up with this solution, and for straitening the floating text. At the moment, I’m getting a 504 bad gateway timeout, so I cannot see the page images. Is this part of the slow webhooks situation? John
