### ISSUE TITLE
Coursepacks not working in dev?

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-data#2]
Hi, @wsalesky! It seems like the coursepack feature isn't working in the dev site anymore--it may be because of that docker reset?

**Comment by wsalesky** [comment]
Yes, you were right. I just reran the:

`sm:chmod(xs:anyURI('/db/apps/LiC/modules/lib/coursepack.xql'), "rwsrwxr-x")`

To give it the correct permissions. Seems to work okay now.
