### ISSUE TITLE
Merges are doubling, not replacing

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-data#34]
I recently did a merge on the data repo from development-->dev2master-->master, and all seemed to work well. However, the app is not replacing older files, but instead doubling them. In these two texts, for instance, one has notes and the title is in "quotation marks" (the most recent one), but the older text is still there:

<img width="1731" alt="Screen Shot 2023-04-10 at 9 23 27 AM" src="https://user-images.githubusercontent.com/1153464/230909676-87563c43-9631-400c-9ff8-445636add614.png">

**Comment by wsalesky** [comment]
@tonyahowe  How does it look now?

**Comment by wsalesky** [comment]
@tonyahowe Did you change the data structure at all? Sometimes the webhooks fail to deal with deletes correctly. There was a /data directory nested inside the main /data directory, so there were duplicates on the server, but not on GitHub. I just redeployed the data, so everything should be good now.
