### ISSUE TITLE
"by Phillis Wheatley by Phillis Wheatley"

### ISSUE THREAD

**Issue by tonyahowe** [LiteratureInContext/LiC-data#4]
In the Wheatley poems, it seems that the main title in the TEI includes "by Phillis Wheatley," which causes her name to be duplicated. We need to remove all the names included in the titles:
```
<titleStmt>
<title type="main"> "A Farewel to AMERICA" by Phillis Wheatley</title>
```
<img width="779" alt="Screen Shot 2019-03-15 at 7 41 09 PM" src="https://user-images.githubusercontent.com/1153464/54467317-b0c77080-475a-11e9-85fb-f2c3d41a2a62.png">

**Comment by brinascode** [comment]
Solved!
