### ISSUE TITLE
images

### ISSUE THREAD

**Issue by jobrien62** [LiteratureInContext/LiC-data#6]
The file path for page images is a little wonky. I put images for Franklin's Autobiography in the AWS container, but eXist redirects to the older version of the site on Tonya's Github for page images, while being fine with images that are now within notes (see several of the notes in Franklin, for example). That's where the images for Finch are housed. I don't want to break one thing to fix another, but we'll have to be consistent, I assume.

**Comment by tonyahowe** [comment]
This should be working now! See [https://github.com/LiteratureInContext/LiC-app/issues/28](https://github.com/LiteratureInContext/LiC-app/issues/28 )
